const defaultStructure = {
  8: {
    rcl: 8,
    buildings: {
      spawn: {
        pos: [
          { x: 18, y: 13 },
          { x: 23, y: 22 },
          { x: 28, y: 17 },
        ],
      },
      extension: {
        pos: [
          { x: 25, y: 16 },
          { x: 26, y: 16 },
          { x: 26, y: 17 },
          { x: 25, y: 15 },
          { x: 24, y: 15 },
          { x: 23, y: 14 },
          { x: 23, y: 15 },
          { x: 24, y: 14 },
          { x: 26, y: 14 },
          { x: 27, y: 15 },
          { x: 27, y: 14 },
          { x: 28, y: 15 },
          { x: 28, y: 14 },
          { x: 27, y: 13 },
          { x: 27, y: 18 },
          { x: 28, y: 18 },
          { x: 24, y: 19 },
          { x: 23, y: 19 },
          { x: 23, y: 20 },
          { x: 22, y: 20 },
          { x: 21, y: 20 },
          { x: 22, y: 21 },
          { x: 21, y: 19 },
          { x: 20, y: 19 },
          { x: 20, y: 18 },
          { x: 19, y: 18 },
          { x: 20, y: 17 },
          { x: 21, y: 17 },
          { x: 21, y: 14 },
          { x: 20, y: 15 },
          { x: 19, y: 15 },
          { x: 19, y: 16 },
          { x: 19, y: 14 },
          { x: 18, y: 17 },
          { x: 18, y: 16 },
          { x: 18, y: 15 },
          { x: 18, y: 14 },
          { x: 24, y: 21 },
          { x: 24, y: 22 },
          { x: 21, y: 22 },
          { x: 20, y: 21 },
          { x: 19, y: 20 },
          { x: 18, y: 19 },
          { x: 18, y: 20 },
          { x: 18, y: 21 },
          { x: 19, y: 21 },
          { x: 20, y: 22 },
          { x: 19, y: 22 },
          { x: 26, y: 13 },
          { x: 25, y: 13 },
          { x: 25, y: 12 },
          { x: 26, y: 12 },
          { x: 21, y: 13 },
          { x: 22, y: 13 },
          { x: 22, y: 12 },
          { x: 21, y: 12 },
          { x: 20, y: 12 },
          { x: 20, y: 13 },
          { x: 23, y: 12 },
          { x: 27, y: 12 },
        ],
      },
      storage: { pos: [{ x: 23, y: 16 }] },
      tower: {
        pos: [
          { x: 25, y: 17 },
          { x: 25, y: 18 },
          { x: 22, y: 15 },
          { x: 21, y: 18 },
          { x: 22, y: 19 },
          { x: 21, y: 16 },
        ],
      },
      lab: {
        pos: [
          { x: 25, y: 20 },
          { x: 25, y: 21 },
          { x: 26, y: 22 },
          { x: 26, y: 21 },
          { x: 27, y: 22 },
          { x: 28, y: 21 },
          { x: 27, y: 20 },
          { x: 26, y: 19 },
          { x: 27, y: 19 },
          { x: 28, y: 20 },
        ],
      },
      observer: { pos: [{ x: 25, y: 22 }] },
      powerSpawn: { pos: [{ x: 19, y: 12 }] },
      nuker: { pos: [{ x: 24, y: 16 }] },
      terminal: { pos: [{ x: 24, y: 17 }] },
      container: { pos: [] },
      link: { pos: [{ x: 22, y: 18 }] },
      extractor: { pos: [] },
      rampart: { pos: [] },
      factory: { pos: [{ x: 28, y: 13 }] },
    },
  },
  7: {
    rcl: 7,
    buildings: {
      spawn: {
        pos: [
          { x: 18, y: 13 },
          { x: 23, y: 22 },
        ],
      },
      extension: {
        pos: [
          { x: 25, y: 16 },
          { x: 26, y: 16 },
          { x: 26, y: 17 },
          { x: 25, y: 15 },
          { x: 24, y: 15 },
          { x: 23, y: 14 },
          { x: 23, y: 15 },
          { x: 24, y: 14 },
          { x: 26, y: 14 },
          { x: 27, y: 15 },
          { x: 27, y: 14 },
          { x: 28, y: 15 },
          { x: 28, y: 14 },
          { x: 27, y: 13 },
          { x: 27, y: 18 },
          { x: 24, y: 19 },
          { x: 23, y: 19 },
          { x: 23, y: 20 },
          { x: 22, y: 20 },
          { x: 21, y: 20 },
          { x: 22, y: 21 },
          { x: 21, y: 19 },
          { x: 20, y: 19 },
          { x: 20, y: 18 },
          { x: 19, y: 18 },
          { x: 20, y: 17 },
          { x: 21, y: 17 },
          { x: 21, y: 14 },
          { x: 20, y: 15 },
          { x: 19, y: 15 },
          { x: 19, y: 16 },
          { x: 19, y: 14 },
          { x: 18, y: 17 },
          { x: 18, y: 16 },
          { x: 18, y: 15 },
          { x: 18, y: 14 },
          { x: 24, y: 21 },
          { x: 24, y: 22 },
          { x: 26, y: 13 },
          { x: 25, y: 13 },
          { x: 25, y: 12 },
          { x: 26, y: 12 },
          { x: 21, y: 13 },
          { x: 22, y: 13 },
          { x: 22, y: 12 },
          { x: 21, y: 12 },
          { x: 20, y: 12 },
          { x: 20, y: 13 },
          { x: 23, y: 12 },
          { x: 28, y: 18 },
        ],
      },
      storage: { pos: [{ x: 23, y: 16 }] },
      tower: {
        pos: [
          { x: 25, y: 17 },
          { x: 22, y: 15 },
          { x: 22, y: 19 },
        ],
      },
      lab: {
        pos: [
          { x: 25, y: 20 },
          { x: 25, y: 21 },
          { x: 26, y: 21 },
          { x: 27, y: 20 },
          { x: 26, y: 19 },
          { x: 27, y: 19 },
        ],
      },
      observer: { pos: [] },
      powerSpawn: { pos: [] },
      nuker: { pos: [] },
      terminal: { pos: [{ x: 24, y: 17 }] },
      container: { pos: [] },
      link: { pos: [{ x: 22, y: 18 }] },
      extractor: { pos: [] },
      rampart: { pos: [] },
      factory: { pos: [{ x: 28, y: 13 }] },
    },
  },
  6: {
    rcl: 6,
    buildings: {
      spawn: { pos: [{ x: 18, y: 13 }] },
      extension: {
        pos: [
          { x: 25, y: 16 },
          { x: 26, y: 16 },
          { x: 26, y: 17 },
          { x: 25, y: 15 },
          { x: 24, y: 15 },
          { x: 23, y: 14 },
          { x: 23, y: 15 },
          { x: 24, y: 14 },
          { x: 27, y: 18 },
          { x: 24, y: 19 },
          { x: 23, y: 19 },
          { x: 23, y: 20 },
          { x: 22, y: 20 },
          { x: 21, y: 20 },
          { x: 22, y: 21 },
          { x: 21, y: 19 },
          { x: 20, y: 19 },
          { x: 20, y: 18 },
          { x: 19, y: 18 },
          { x: 20, y: 17 },
          { x: 21, y: 17 },
          { x: 21, y: 14 },
          { x: 20, y: 15 },
          { x: 19, y: 15 },
          { x: 19, y: 16 },
          { x: 19, y: 14 },
          { x: 18, y: 17 },
          { x: 18, y: 16 },
          { x: 18, y: 15 },
          { x: 18, y: 14 },
          { x: 24, y: 21 },
          { x: 24, y: 22 },
          { x: 21, y: 13 },
          { x: 22, y: 13 },
          { x: 22, y: 12 },
          { x: 21, y: 12 },
          { x: 20, y: 12 },
          { x: 20, y: 13 },
          { x: 23, y: 12 },
          { x: 28, y: 18 },
        ],
      },
      storage: { pos: [{ x: 23, y: 16 }] },
      tower: {
        pos: [
          { x: 22, y: 15 },
          { x: 22, y: 19 },
        ],
      },
      lab: {
        pos: [
          { x: 27, y: 20 },
          { x: 26, y: 19 },
          { x: 27, y: 19 },
        ],
      },
      observer: { pos: [] },
      powerSpawn: { pos: [] },
      nuker: { pos: [] },
      terminal: { pos: [{ x: 24, y: 17 }] },
      container: { pos: [] },
      link: { pos: [{ x: 22, y: 18 }] },
      extractor: { pos: [] },
      rampart: { pos: [] },
      factory: { pos: [] },
    },
  },
  5: {
    rcl: 5,
    buildings: {
      spawn: { pos: [{ x: 18, y: 13 }] },
      extension: {
        pos: [
          { x: 25, y: 16 },
          { x: 26, y: 16 },
          { x: 26, y: 17 },
          { x: 25, y: 15 },
          { x: 24, y: 15 },
          { x: 23, y: 14 },
          { x: 23, y: 15 },
          { x: 24, y: 14 },
          { x: 24, y: 19 },
          { x: 23, y: 19 },
          { x: 23, y: 20 },
          { x: 22, y: 20 },
          { x: 21, y: 20 },
          { x: 22, y: 21 },
          { x: 21, y: 19 },
          { x: 20, y: 19 },
          { x: 20, y: 18 },
          { x: 19, y: 18 },
          { x: 20, y: 17 },
          { x: 21, y: 17 },
          { x: 21, y: 14 },
          { x: 20, y: 15 },
          { x: 19, y: 15 },
          { x: 19, y: 16 },
          { x: 19, y: 14 },
          { x: 18, y: 17 },
          { x: 18, y: 16 },
          { x: 18, y: 15 },
          { x: 18, y: 14 },
          { x: 21, y: 13 },
        ],
      },
      storage: { pos: [{ x: 23, y: 16 }] },
      tower: {
        pos: [
          { x: 22, y: 15 },
          { x: 22, y: 19 },
        ],
      },
      lab: { pos: [] },
      observer: { pos: [] },
      powerSpawn: { pos: [] },
      nuker: { pos: [] },
      terminal: { pos: [] },
      container: { pos: [] },
      link: { pos: [{ x: 22, y: 18 }] },
      extractor: { pos: [] },
      rampart: { pos: [] },
      factory: { pos: [] },
    },
  },
  4: {
    rcl: 4,
    buildings: {
      spawn: { pos: [{ x: 18, y: 13 }] },
      extension: {
        pos: [
          { x: 25, y: 16 },
          { x: 26, y: 16 },
          { x: 26, y: 17 },
          { x: 25, y: 15 },
          { x: 24, y: 15 },
          { x: 23, y: 14 },
          { x: 23, y: 15 },
          { x: 24, y: 14 },
          { x: 24, y: 19 },
          { x: 23, y: 19 },
          { x: 23, y: 20 },
          { x: 22, y: 20 },
          { x: 21, y: 20 },
          { x: 22, y: 21 },
          { x: 21, y: 19 },
          { x: 20, y: 19 },
          { x: 20, y: 18 },
          { x: 19, y: 18 },
          { x: 20, y: 17 },
          { x: 21, y: 17 },
        ],
      },
      storage: { pos: [{ x: 23, y: 16 }] },
      tower: { pos: [{ x: 22, y: 19 }] },
      lab: { pos: [] },
      observer: { pos: [] },
      powerSpawn: { pos: [] },
      nuker: { pos: [] },
      terminal: { pos: [] },
      container: { pos: [] },
      link: { pos: [] },
      extractor: { pos: [] },
      rampart: { pos: [] },
      factory: { pos: [] },
    },
  },
  3: {
    rcl: 3,
    buildings: {
      spawn: { pos: [{ x: 18, y: 13 }] },
      extension: {
        pos: [
          { x: 24, y: 19 },
          { x: 23, y: 19 },
          { x: 23, y: 20 },
          { x: 22, y: 20 },
          { x: 21, y: 20 },
          { x: 21, y: 19 },
          { x: 20, y: 19 },
          { x: 20, y: 18 },
          { x: 20, y: 17 },
          { x: 21, y: 17 },
        ],
      },
      storage: { pos: [] },
      tower: { pos: [{ x: 22, y: 19 }] },
      lab: { pos: [] },
      observer: { pos: [] },
      powerSpawn: { pos: [] },
      nuker: { pos: [] },
      terminal: { pos: [] },
      container: { pos: [] },
      link: { pos: [] },
      extractor: { pos: [] },
      rampart: { pos: [] },
      factory: { pos: [] },
    },
  },
  2: {
    rcl: 2,
    buildings: {
      spawn: { pos: [{ x: 18, y: 13 }] },
      extension: {
        pos: [
          { x: 23, y: 19 },
          { x: 22, y: 20 },
          { x: 21, y: 19 },
          { x: 20, y: 19 },
          { x: 20, y: 18 },
        ],
      },
      storage: { pos: [] },
      tower: { pos: [] },
      lab: { pos: [] },
      observer: { pos: [] },
      powerSpawn: { pos: [] },
      nuker: { pos: [] },
      terminal: { pos: [] },
      container: { pos: [] },
      link: { pos: [] },
      extractor: { pos: [] },
      rampart: { pos: [] },
      factory: { pos: [] },
    },
  },
  1: {
    rcl: 1,
    buildings: {
      spawn: { pos: [{ x: 18, y: 13 }] },
      extension: { pos: [] },
      storage: { pos: [] },
      tower: { pos: [] },
      lab: { pos: [] },
      observer: { pos: [] },
      powerSpawn: { pos: [] },
      nuker: { pos: [] },
      terminal: { pos: [] },
      container: { pos: [] },
      link: { pos: [] },
      extractor: { pos: [] },
      rampart: { pos: [] },
      factory: { pos: [] },
    },
  },
};
/**
 * @date 2022-01-10
 * @param {number} rcl
 * @param {{x: number, y: number}} sourceSpawnPos
 * @returns {void}
 */
Room.prototype.displayPlan = function (rcl, sourceSpawnPos) {
  const planSpawnPos = defaultStructure[1].buildings.spawn.pos[0];
  const indent = {
    x: sourceSpawnPos.x - planSpawnPos.x,
    y: sourceSpawnPos.y - planSpawnPos.y,
  };
  const plan = defaultStructure[rcl].buildings;
  for (const buildingName in plan) {
    const building = plan[buildingName];
    for (const pos of building.pos) {
      const x = pos.x + indent.x;
      const y = pos.y + indent.y;
      this.visual.structure(x, y, buildingName, { opacity: 0.5 });
    }
  }
};
